# DevSpace configuration for ark-broker service
version: v2beta1

pipelines:
  deploy: |-
    build_images --all
    create_deployments --all
  dev: |-
    create_deployments --all
    start_dev --all

images:
  ark-broker:
    image: ark-broker
    dockerfile: ./ark-broker/Dockerfile
    context: ./ark-broker

deployments:
  ark-broker:
    namespace: default
    helm:
      chart:
        path: ./chart
      values:
        app:
          image:
            repository: ${runtime.images.ark-broker.image}
            tag: ${runtime.images.ark-broker.tag}
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
            requests:
              memory: "256Mi"
              cpu: "200m"
        # Override security context for dev mode to allow DevSpace sync
        podSecurityContext:
          runAsNonRoot: false
          runAsUser: 0
          fsGroup: 0
        securityContext:
          runAsUser: 0
          allowPrivilegeEscalation: true
          readOnlyRootFilesystem: false
          capabilities:
            add:
              - SETUID
              - SETGID
              - CHOWN
              - FOWNER
              - DAC_OVERRIDE
        memory:
          setAsDefault: true
        persistence:
          enabled: true
          size: 1Gi
        otelEnvironmentVariableSecrets:
          enabled: true
          namespaces:
            - ark-system
            - default

dev:
  ark-broker:
    imageSelector: ark-broker
    devImage: node:24-alpine
    command: ["sh", "-c", "cd /app && npm install && npm run dev"]
    namespace: default
    logs:
      lastLines: 50
    sync:
      - path: ./ark-broker:/app
        startContainer: true
        disableDownload: true
        uploadExcludeFile: .dockerignore
    ssh:
      enabled: true
